# Use the official Maven image to build the Java application
FROM maven:3.8.4-openjdk-8 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
COPY . .

# Build the Java application
RUN mvn clean package

# Use the official Tomcat image with Java 8
FROM tomcat:8-jre8

# Set environment variables
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

# Remove the default Tomcat webapps
RUN rm -rf $CATALINA_HOME/webapps/*

# Copy the generated war file into the webapps directory
COPY --from=build /app/target/rest_item-1.0-SNAPSHOT.war $CATALINA_HOME/webapps/

# Expose the default Tomcat port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]